import type { Metadata } from "next";
import "@/app/globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false; 

export const metadata: Metadata = {
  title: "Wiwit Aditya - Street Food",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <head>
        <link rel="stylesheet" href="/css/bootstrap.min.css"></link>
        <link rel="stylesheet" href="/css/slick.css"></link>
        <link rel="stylesheet" href="/css/nice-select.css"></link>
        <link rel="stylesheet" href="/css/custom_spacing.css"></link>
        <link rel="stylesheet" href="/css/venobox.min.css"></link>
        <link rel="stylesheet" href="/css/animate.css"></link>
        <link rel="stylesheet" href="/css/jquery.exzoom.css"></link>
        <link rel="stylesheet" href="/css/style.css"></link>
        <link rel="stylesheet" href="/css/responsive.css"></link>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
