import type { Metadata } from "next";
import "@/app/globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; 
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub, faUpwork } from "@fortawesome/free-brands-svg-icons";

import { cookiesGetUserId } from "@/app/lib/util/cookie-util";
import DashboardNav from "@/app/ui/dashhboard-nav/dashboard-nav";
import { countUserCartByUserAndFlag } from "./lib/database/database";
import { UserCartDbFlag } from "./lib/database/database.definition";
import dynamic from "next/dynamic";

const ReduxProvider = dynamic(() => import("@/app/lib/util/redux-provider/redux-provider"));


export const metadata: Metadata = {
  title: "Wiwit Aditya - Street Food",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await cookiesGetUserId();
  const totalCartDb = await countUserCartByUserAndFlag(userId, UserCartDbFlag.ACTIVE);

  return (
    <html
      lang="en"
    >
      <head>
        <link rel="stylesheet" href="/css/bootstrap.min.css"></link>
        <link rel="stylesheet" href="/css/slick.css"></link>
        <link rel="stylesheet" href="/css/nice-select.css"></link>
        <link rel="stylesheet" href="/css/custom_spacing.css"></link>
        <link rel="stylesheet" href="/css/venobox.min.css"></link>
        <link rel="stylesheet" href="/css/animate.css"></link>
        <link rel="stylesheet" href="/css/jquery.exzoom.css"></link>
        <link rel="stylesheet" href="/css/style.css"></link>
        <link rel="stylesheet" href="/css/responsive.css"></link>
      </head>
      <body>
        <section className="topbar">
          <div className="container">
              <div className="row">
                  <div className="col-xl-6 col-sm-6 col-md-6 col-8">
                      <ul className="topbar_info d-flex flex-wrap">
                          <li>
                            <a href="mailto:wiwit.aditya.saputra@gmail.com">
                              <i className="fas fa-envelope" aria-hidden="true"></i>
                              wiwit.aditya.saputra@gmail.com
                            </a>
                          </li>
                      </ul>
                  </div>
                  <div className="col-xl-6 col-sm-6 col-md-6 col-4">
                      <ul className="topbar_icon d-flex flex-wrap">
                          <li>
                            <a target='_blank' href="https://www.upwork.com/freelancers/wiwitadityasaputra">
                              <FontAwesomeIcon icon={faUpwork} size="sm" />
                            </a>
                          </li>
                          <li>
                            <a target='_blank' href="https://github.com/wiwitadityasaputra#">
                              <FontAwesomeIcon icon={faGithub} size="sm" />
                            </a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
        </section>

        <ReduxProvider>
          <DashboardNav totalCart={totalCartDb} />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
