Parameters:
  ConnectionArn:
    Description: The CodeConnections ARN for your Docker container source repository.
    Type: String
  FullRepositoryId:
    Description: The full repository ID to use with your CodeConnections connection.
    Type: String
  BranchName:
    Description: The branch name to use with your CodeConnections connection.
    Type: String
  CodePipelineName:
    Description: The CodePipeline pipeline name that will build and deploy your
      Docker image from source code.
    Type: String
    Default: SimpleDockerService
  DockerBuildContext:
    Description: The set of files Docker build can acccess.
    Type: String
    Default: .
  DockerFilePath:
    Description: Path to the Dockerfile.
    Type: String
    Default: ./Dockerfile
  ImageTag:
    Description: The image tag to use when building and deploying your Docker image.
    Type: String
    Default: latest
  RetentionPolicy:
    Description: Define if you'd like the resource retained or deleted when the
      CloudFormation stack is deleted.
    Type: String
    Default: Delete

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join
        - '-'
        - - simple-docker-service
          - !Select
            - 4
            - !Split
              - '-'
              - !Select
                - 2
                - !Split
                  - /
                  - !Ref AWS::StackId
    UpdateReplacePolicy: !Ref RetentionPolicy
    DeletionPolicy: !Ref RetentionPolicy
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub
                    - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${projectName}
                    - projectName: !Join
                        - '-'
                        - - SimpleDockerProject
                          - !Select
                            - 4
                            - !Split
                              - '-'
                              - !Select
                                - 2
                                - !Split
                                  - /
                                  - !Ref AWS::StackId
                  - !Sub
                    - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${projectName}:*
                    - projectName: !Join
                        - '-'
                        - - SimpleDockerProject
                          - !Select
                            - 4
                            - !Split
                              - '-'
                              - !Select
                                - 2
                                - !Split
                                  - /
                                  - !Ref AWS::StackId
              - Action:
                  - codebuild:BatchPutCodeCoverages
                  - codebuild:BatchPutTestCases
                  - codebuild:CreateReport
                  - codebuild:CreateReportGroup
                  - codebuild:UpdateReport
                Effect: Allow
                Resource: !Sub
                  - arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${projectName}-*
                  - projectName: !Join
                      - '-'
                      - - SimpleDockerProject
                        - !Select
                          - 4
                          - !Split
                            - '-'
                            - !Select
                              - 2
                              - !Split
                                - /
                                - !Ref AWS::StackId
              - Action:
                  - s3:GetBucket*
                  - s3:GetObject*
                  - s3:List*
                Effect: Allow
                Resource:
                  - !GetAtt CodePipelineArtifactsBucket.Arn
                  - !Sub
                    - ${arn}/*
                    - arn: !GetAtt CodePipelineArtifactsBucket.Arn
              - Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Effect: Allow
                Resource: !GetAtt EcrRepository.Arn
              - Action: ecr:GetAuthorizationToken
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: CodeBuildProjectRoleDefaultPolicy
  CodeBuildDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/
                  - !Join
                    - '-'
                    - - SimpleDockerProject
                      - !Select
                        - 4
                        - !Split
                          - '-'
                          - !Select
                            - 2
                            - !Split
                              - /
                              - !Ref AWS::StackId
                  - ':*'
              - !Join
                - ''
                - - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/
                  - !Join
                    - '-'
                    - - SimpleDockerProject
                      - !Select
                        - 4
                        - !Split
                          - '-'
                          - !Select
                            - 2
                            - !Split
                              - /
                              - !Ref AWS::StackId
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource: !Join
              - ''
              - - !Sub arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/
                - !Join
                  - '-'
                  - - SimpleDockerProject
                    - !Select
                      - 4
                      - !Split
                        - '-'
                        - !Select
                          - 2
                          - !Split
                            - /
                            - !Ref AWS::StackId
                - '-*'
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
      PolicyName: CodeBuildDefaultPolicy
      Roles:
        - !Ref CodeBuildRole
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      Description: Build Docker Image from source code
      EncryptionKey: alias/aws/s3
      Environment:
        EnvironmentVariables:
          - Name: ImageName
            Type: PLAINTEXT
            Value: !Join
              - '-'
              - - simple-docker-service
                - !Select
                  - 4
                  - !Split
                    - '-'
                    - !Select
                      - 2
                      - !Split
                        - /
                        - !Ref AWS::StackId
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name: !Join
        - '-'
        - - SimpleDockerProject
          - !Select
            - 4
            - !Split
              - '-'
              - !Select
                - 2
                - !Split
                  - /
                  - !Ref AWS::StackId
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        BuildSpec: !Sub |
          version: "0.2"
          phases:
            pre_build:
              commands:
                - aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
            build:
              commands:
                - docker build -t $ImageName -f ${DockerFilePath} ${DockerBuildContext}
                - docker images
            post_build:
              commands:
                - docker tag $ImageName:${ImageTag} ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/$ImageName:${ImageTag}
                - docker push ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/$ImageName:${ImageTag}
        Type: NO_SOURCE
  CodePipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: !Ref RetentionPolicy
    DeletionPolicy: !Ref RetentionPolicy
  CodePipelineArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodePipelineArtifactsBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Effect: Deny
            Principal:
              AWS: '*'
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
  CodePipelineDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              - !GetAtt CodeBuildActionRole.Arn
              - !GetAtt CodeConnectionsActionRole.Arn
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Sub
                - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codepipeline/${pipelineName}
                - pipelineName: !Ref CodePipelineName
              - !Sub
                - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codepipeline/${pipelineName}:*
                - pipelineName: !Ref CodePipelineName
        Version: '2012-10-17'
      PolicyName: CodePipelineDefaultPolicy
      Roles:
        - !Ref CodePipelineRole
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref CodePipelineArtifactsBucket
        Type: S3
      ExecutionMode: QUEUED
      Name: !Ref CodePipelineName
      PipelineType: V2
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: CodeConnections
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SourceOutput
              RoleArn: !GetAtt CodeConnectionsActionRole.Arn
              RunOrder: 1
          OnFailure:
            Result: RETRY
        - Name: Build_and_Deploy
          OnFailure:
            Result: ROLLBACK
          BeforeEntry:
            Conditions:
              - Result: FAIL
                Rules:
                  - Name: MyDeploymentWindowRule
                    RuleTypeId:
                      Category: Rule
                      Owner: AWS
                      Provider: DeploymentWindow
                      Version: '1'
                    Configuration:
                      Cron: '* * * * * ? *'
                      TimeZone: PST
          Actions:
            - Name: Docker_Build_Tag_and_Push
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Join
                  - '-'
                  - - SimpleDockerProject
                    - !Select
                      - 4
                      - !Split
                        - '-'
                        - !Select
                          - 2
                          - !Split
                            - /
                            - !Ref AWS::StackId
              InputArtifacts:
                - Name: SourceOutput
              RoleArn: !GetAtt CodeBuildActionRole.Arn
              RunOrder: 1
    DependsOn:
      - CodePipelineDefaultPolicy
  CodeConnectionsActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
  CodeConnectionsActionDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: codestar-connections:UseConnection
            Effect: Allow
            Resource: !Ref ConnectionArn
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
          - Action:
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
            Effect: Allow
            Resource: !Join
              - /
              - - !GetAtt CodePipelineArtifactsBucket.Arn
                - '*'
        Version: '2012-10-17'
      PolicyName: CodeConnectionsActionDefaultPolicy
      Roles:
        - !Ref CodeConnectionsActionRole
  CodeBuildActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
  CodeBuildActionDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource: !GetAtt CodeBuildProject.Arn
        Version: '2012-10-17'
      PolicyName: CodeBuildActionDefaultPolicy
      Roles:
        - !Ref CodeBuildActionRole

        