import type { Metadata } from "next";
import dynamic from "next/dynamic";

import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; 
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub, faUpwork } from "@fortawesome/free-brands-svg-icons";

import "@/src/app/globals.css";
import { cookiesGetUserId } from "@/src/lib/util/cookie-util";
import DashboardNav from "@/src/ui/dashhboard-nav/dashboard-nav";
import { countUserCartByUserAndFlag } from "@/src/lib/database/database";
import { UserCartDbFlag } from "@/src/lib/database/database.definition";
import { QueueMenu } from "@/src/ui/queue/queue-menu/queue-menu";
import { countAllOrdersPage, countUserOrders } from "@/src/lib/service/queue.service";
import { NUMBER_PER_PAGE } from "@/src/ui/queue/all/queue-all.definition";

const ReduxProvider = dynamic(() => import("@/src/lib/util/redux-provider/redux-provider"));

export const metadata: Metadata = {
  title: "Wiwit Aditya - Street Food",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await cookiesGetUserId();
  const totalCartDb = await countUserCartByUserAndFlag(userId, UserCartDbFlag.ACTIVE);

  const userTotalOrder = await countUserOrders(userId);
  const totalAllOrders = await countAllOrdersPage();

  return (
    <>
        <section className="topbar">
          <div className="container">
              <div className="row">
                  <div className="col-xl-6 col-sm-6 col-md-6 col-8">
                      <ul className="topbar_info d-flex flex-wrap">
                          <li>
                            <a href="mailto:wiwit.aditya.saputra@gmail.com">
                              <i className="fas fa-envelope" aria-hidden="true"></i>
                              wiwit.aditya.saputra@gmail.com
                            </a>
                          </li>
                      </ul>
                  </div>
                  <div className="col-xl-6 col-sm-6 col-md-6 col-4">
                      <ul className="topbar_icon d-flex flex-wrap">
                          <li>
                            <a target='_blank' href="https://www.upwork.com/freelancers/wiwitadityasaputra">
                              <FontAwesomeIcon icon={faUpwork} size="sm" />
                            </a>
                          </li>
                          <li>
                            <a target='_blank' href="https://github.com/wiwitadityasaputra#">
                              <FontAwesomeIcon icon={faGithub} size="sm" />
                            </a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
        </section>

        <ReduxProvider>
          <DashboardNav totalCart={totalCartDb} />
          <QueueMenu
            userTotalOrder={userTotalOrder}
            totalOrders={totalAllOrders}
          />
          {children}
        </ReduxProvider>
    </>
  );
}
